### ISSUE TITLE
Downloader 

### ISSUE THREAD

**Issue by Kingsasha23** [sheikhhaziq/vibemusic#67]
### Feature description

Music downloader with Lyrics Please

**Comment by sheikhhaziq** [comment]
Next update will be having downloader

**Comment by sheikhhaziq** [comment]
downloader has been added in latest beta release and lyrics will be available soon as well.

**Comment by DarkCrypt** [comment]
Downloader doesn't download and permissions are greyed out in App Info screen, v0.9.0 beta, on Android 13.

**Comment by owencz1998** [comment]
Yes iv faced the same issue I have some new permissions on standby that I would like to test but having issues with my laptop 🤦‍♂️

**Comment by sheikhhaziq** [comment]
Downloader problems with android 13 have been fixed

**Comment by DarkCrypt** [comment]
V0.9.1 still can't download. Push download -> app sends user to App Info screen -> permissions are greyed out and notifications cannot be toggled.

**Comment by owencz1998** [comment]
Have u tried to clear data and cache

**Comment by sheikhhaziq** [comment]
> V0.9.1 still can't download. Push download -> app sends user to App Info screen -> permissions are greyed out and notifications cannot be toggled.

Can you share the screenshot or screen recording of the problem you are having.

**Comment by DarkCrypt** [comment]
I cleared data and cache multiple times, forced stopped app, and I even restarted my phone. Same result.

https://user-images.githubusercontent.com/121076677/221373537-9fc2ef6d-9c31-4f6f-b876-0a76d8dc8f42.mp4

**Comment by sheikhhaziq** [comment]
Can you specify your device and os

**Comment by DarkCrypt** [comment]
OnePlus 9 Pro, Android 13, OxygenOS 13. System is up to date.

**Comment by owencz1998** [comment]
Has your phone got a special access section in settings in apps/storage as there's a setting that can give the app full access

**Comment by owencz1998** [comment]
As i use samsung but the permissions don't show but there is a setting for special access that allows the app to have access to the storage and it allows me to now download

**Comment by DarkCrypt** [comment]
Yes sir, I do have special app access in settings with all files access toggled on. Same result.

![Screenshot_2023-02-25-14-32-27-86_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/121076677/221378594-6d902a59-d9ed-48c2-bc54-bed4359097ec.jpg)

**Comment by owencz1998** [comment]
Ahh ok these permissions on all devices seem to be a headache hopefully there will be a fix soon

**Comment by DarkCrypt** [comment]
I hear that, I hope so too. These permissions have been a big pain in the ass for many devs lately. It's definitely been a struggle, not sure what the deal is.

**Comment by DarkCrypt** [comment]
I forgot to tell you guys... I can produce logs via adb if that would be helpful.

**Comment by DarkCrypt** [comment]
Ok. Before I started I cleared all data and cache from vibe music. Then I logged searching a song, trying to download song from search results, playing song from search results, and trying to download song from player. Similar to above screen recording.
[vibemusicop9proa13log.txt](https://github.com/sheikhhaziq/vibemusic/files/10836819/vibemusicop9proa13log.txt)

**Comment by DarkCrypt** [comment]
@sheikhhaziq 
I was just curious if you were able to get any useful information from logcat I sent?

**Comment by sheikhhaziq** [comment]
Not really

**Comment by DarkCrypt** [comment]
@sheikhhaziq 
I was wondering if you would like to look into this or possibly test these permissions. These permissions are from a similar music streaming/downloader app which I've given tons of feedback to the dev. After lots of trial and error, this is what the dev came up with and it works for Android 13. If you compare these permissions to Vibe Music, you'll see the differences. Up to you.
 
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" android:maxSdkVersion="32"
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"
uses-permission android:name="android.permission.READ_MEDIA_AUDIO"
uses-permission android:name="android.permission.INTERNET"
uses-permission android:name="android.permission.WAKE_LOCK"
uses-permission android:name="android.permission.FOREGROUND_SERVICE"
uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"
uses-permission android:name="android.permission.POST_NOTIFICATIONS"
